removed GitScraper

diff --git a/.github/workflows/create-release.yml b/.github/workflows/create-release.yml
--- a/.github/workflows/create-release.yml
+++ b/.github/workflows/create-release.yml
@@ -37,29 +37,29 @@ jobs:
       - name: Build
         run: dotnet build --no-restore
 
-      - name: Log in to Docker Hub
-        run: |
-          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
+#      - name: Log in to Docker Hub
+#        run: |
+#          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
 
-      - name: Pull and run GitScraper container
-        run: |
-          docker pull rasmusrlarsen/gitscraper:latest
-          docker run -d -p 8080:8080 rasmusrlarsen/gitscraper:latest
-          sleep 10
+#      - name: Pull and run GitScraper container
+#        run: |
+#          docker pull rasmusrlarsen/gitscraper:latest
+#          docker run -d -p 8080:8080 rasmusrlarsen/gitscraper:latest
+#          sleep 10
 
-      - name: Fetch chart
-        run: |
-          RESPONSE_HEADERS=$(mktemp)
-          curl -L -s -o timechart.png -D $RESPONSE_HEADERS \
-            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
-            "http://localhost:8080/generate-chart?org=ITU-DevOps2025-GROUP-A&repo=itu-minitwit"
+#      - name: Fetch chart
+#        run: |
+#          RESPONSE_HEADERS=$(mktemp)
+#          curl -L -s -o timechart.png -D $RESPONSE_HEADERS \
+#            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
+#            "http://localhost:8080/generate-chart?org=ITU-DevOps2025-GROUP-A&repo=itu-minitwit"
           
-          CONTENT_TYPE=$(grep -i "Content-Type:" $RESPONSE_HEADERS | awk '{print $2}' | tr -d '\r')
-          if [[ "$CONTENT_TYPE" != "image/png" ]]; then
-            echo "Error: The response is not an image. Possible API failure."
-            cat timechart.png
-            exit 1
-          fi
+#          CONTENT_TYPE=$(grep -i "Content-Type:" $RESPONSE_HEADERS | awk '{print $2}' | tr -d '\r')
+#          if [[ "$CONTENT_TYPE" != "image/png" ]]; then
+#            echo "Error: The response is not an image. Possible API failure."
+#            cat timechart.png
+#            exit 1
+#          fi
 
       - name: Get latest tag
         run: |
