more debugging

diff --git a/.github/workflows/create-release.yml b/.github/workflows/create-release.yml
--- a/.github/workflows/create-release.yml
+++ b/.github/workflows/create-release.yml
@@ -74,8 +74,16 @@ jobs:
       - name: List directory structure - before
         run: ls -R
 
+      - name: Check if directory exists
+        run: |
+          ls ./Api/Api || echo "Directory not found"
+          
+      - name: Check if directory exists
+        run: |
+          ls itu-minitwit/Api/Api || echo "Directory not found"
+
       - name: List directory structure - after
-        working-directory: Api/Api/
+        working-directory: ./Api/Api/
         run: ls -R
   
       - name: release for all platforms - api
